{% set name = "cobble" %}
{% set version = "0.1.4" %}
{% set python_min = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cobble-{{ version }}.tar.gz
  sha256: de38be1539992c8a06e569630717c485a5f91be2192c461ea2b220607dfa78aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - cobble
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://github.com/mwilliamson/python-cobble
  summary: Create data objects
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
